apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boinc

# Name suffix to distinguish DaemonSets
nameSuffix: -highmem

# Common labels for all resources
labels:
  - pairs:
      boinc.homelab/profile: highmem
      boinc.homelab/cpu-tier: low
      boinc.homelab/memory-tier: high

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: boinc-config
  - path: resources.yaml
    target:
      kind: DaemonSet
      name: boinc-client
  - path: node-selector.yaml
    target:
      kind: DaemonSet
      name: boinc-client
