apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boinc

nameSuffix: -highmem

labels:
  - pairs:
      boinc.homelab/profile: highmem
      boinc.homelab/cpu-tier: low
      boinc.homelab/memory-tier: high

resources:
  - ../../base

patches:
  - path: resources.yaml
    target:
      kind: DaemonSet
      name: boinc-client
  - path: node-selector.yaml
    target:
      kind: DaemonSet
      name: boinc-client
