api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: cliff.li@cliff.li
      storage: acme.json
      httpChallenge:
        entryPoint: web

# Automatically redirect HTTP to HTTPS
http:
  redirections:
    entryPoint:
      to: websecure
      scheme: https
      permanent: true
