apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation

resources:
  - storage-pvs.yaml
  - storage-pvcs.yaml
  - zigbee2mqtt.yaml
  - ingress.yaml
  - middleware.yaml

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: zigbee2mqtt
    app.kubernetes.io/component: automation
    app.kubernetes.io/part-of: homelab
