---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-direct
  volumeName: zigbee2mqtt-data
  resources:
    requests:
      storage: 1Gi
