apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utilities

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: whoami
    app.kubernetes.io/component: utilities
    app.kubernetes.io/part-of: homelab

images:
  - name: traefik/whoami
    newTag: latest