apiVersion: v1
kind: Service
metadata:
  name: boinc-gui-rpc
  namespace: boinc
  labels:
    app: boinc-client
spec:
  type: NodePort
  ports:
  - port: 31416
    targetPort: 31416
    nodePort: 31416
    protocol: TCP
    name: gui-rpc
  selector:
    app: boinc-client