---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-thumbs
  namespace: cloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-direct
  volumeName: immich-thumbs
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-encoded-video
  namespace: cloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-direct
  volumeName: immich-encoded-video
  resources:
    requests:
      storage: 30Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-profile
  namespace: cloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-direct
  volumeName: immich-profile
  resources:
    requests:
      storage: 1Gi
