---
# Immich photo library
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - vers=4.1
    - hard
    - timeo=300
    - retrans=3
    - rsize=1048576
    - wsize=1048576
    - _netdev
    
    - noatime
    - actimeo=30
    - lookupcache=positive
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: immich-library
    volumeAttributes:
      server: 192.168.1.94
      share: /media/immich/library

