---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-direct
  mountOptions:
    - vers=4.1
    - hard
    - timeo=300
    - retrans=3
    - rsize=1048576
    - wsize=1048576
    - _netdev
    - noatime
    - actimeo=30
    - lookupcache=positive
  nfs:
    server: 192.168.1.94
    path: /media/immich/library
