---
# Immich photo library
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: cloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  volumeName: immich-library
  resources:
    requests:
      storage: 5Ti

