replicaCount: 2

controllers:
  main:
    containers:
      main:
        image:
          tag: v2.3.1
        env:
          DB_HOSTNAME: immich-postgres
          DB_PORT: "5432"
          DB_USERNAME: immich
          DB_DATABASE_NAME: immich
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-secrets
                key: db-password
          REDIS_HOSTNAME: immich-redis
          REDIS_PORT: "6379"
          IMMICH_MACHINE_LEARNING_ENABLED: "true"

immich:
  persistence:
    library:
      existingClaim: immich-library

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  controllers:
    main:
      containers:
        main:
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi

  ingress:
    main:
      enabled: false  # See ingress.yaml.

machine-learning:
  enabled: true
  controllers:
    main:
      containers:
        main:
          resources:
            requests:
              cpu: 500m
              memory: 1536Mi
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: emptyDir

# External Redis instead, see redis.yaml.
valkey:
  enabled: false

