---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-backups
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-direct
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: 192.168.1.94
    path: /media/games

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backups
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-direct
  volumeName: minecraft-backups
  resources:
    requests:
      storage: 100Gi
