---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-auth
  namespace: monitoring
type: Opaque
data:
  users: Y3lsOiRhcHIxJEFzeTVCcC5yJDU1VGRqT2tGOUFMODF5RUkvSVEzaC8=

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-auth
  namespace: monitoring
spec:
  basicAuth:
    secret: prometheus-auth