apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utilities

resources:
  - storage.yaml
  - syncthing.yaml
  - ingress.yaml

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/component: utilities
    app.kubernetes.io/part-of: homelab

images:
  - name: syncthing/syncthing
    newTag: latest
  - name: alpine/git
    newTag: latest
