apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boinc

nameSuffix: -highcpu

labels:
  - pairs:
      boinc.homelab/profile: highcpu
      boinc.homelab/cpu-tier: high
      boinc.homelab/memory-tier: low

resources:
  - ../../base

patches:
  - path: resources.yaml
    target:
      kind: DaemonSet
      name: boinc-client
  - path: node-selector.yaml
    target:
      kind: DaemonSet
      name: boinc-client
