apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: infrastructure
data:
  traefik.yml: |
    api:
      dashboard: true
      insecure: true

    entryPoints:
      web:
        address: ":80"
        proxyProtocol:
          trustedIPs:
            - "100.121.249.71/32"
      websecure:
        address: ":443"
        proxyProtocol:
          trustedIPs:
            - "100.121.249.71/32"
        http:
          tls: {}
        transport:
          respondingTimeouts:
            readTimeout: "0s"
      minecraft:
        address: ":25565"
      traefik:
        address: ":8080"

    ping: {}

    providers:
      kubernetesIngress: {}
      kubernetesCRD: {}

    # Enable access logs
    accessLog: {}

    # Metrics
    metrics:
      prometheus:
        addEntryPointsLabels: true
        addServicesLabels: true
