apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: infrastructure
data:
  traefik.yml: |
    api:
      dashboard: true
      insecure: true

    entryPoints:
      web:
        address: ":80"
        proxyProtocol:
          trustedIPs:
            - "100.121.249.71/32"
        http:
          redirections:
            entrypoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        address: ":443"
        proxyProtocol:
          trustedIPs:
            - "100.121.249.71/32"
      traefik:
        address: ":8080"

    ping: {}

    providers:
      kubernetesIngress: {}
      kubernetesCRD: {}

    certificatesResolvers:
      letsencrypt:
        acme:
          email: cliff.li@cliff.li
          storage: /acme/acme.json
          httpChallenge:
            entryPoint: web

    # Enable access logs
    accessLog: {}

    # Metrics
    metrics:
      prometheus:
        addEntryPointsLabels: true
        addServicesLabels: true