#!/bin/bash
# NetworkManager dispatcher hook.

INTERFACE=$1
ACTION=$2

if [ "$ACTION" = "up" ]; then
    if ethtool -k "$INTERFACE" 2>/dev/null | grep -q "rx-udp-gro-forwarding"; then
        logger "Enabling UDP GRO forwarding on $INTERFACE for Tailscale"
        ethtool -K "$INTERFACE" rx-udp-gro-forwarding on 2>&1 | logger
    fi
fi
