---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-files
  namespace: cloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-direct
  resources:
    requests:
      storage: 5Ti
  volumeName: nextcloud-files
