---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-direct
  volumeName: home-assistant-config
  resources:
    requests:
      storage: 10Gi
