apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - recorder.yaml
  - frontend.yaml
  - ingress.yaml
  - backup-storage.yaml
  - backup-cronjob.yaml

namespace: location

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: owntracks
    app.kubernetes.io/component: location
    app.kubernetes.io/part-of: homelab