# 4 CPU, 8GB
apiVersion: v1
kind: Node
metadata:
  name: cyl-optiplex9020
  labels:
    homelab/cpu-tier: low
    homelab/memory-tier: low
spec:
  taints:
  - key: workload
    value: essential-only
    effect: NoSchedule
