apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - prometheus/prometheus.yaml
  - prometheus/auth.yaml
  - grafana/grafana.yaml
  - node-exporter/node-exporter.yaml
  - kube-state-metrics/kube-state-metrics.yaml
  - ingress.yaml

namespace: monitoring

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: homelab