---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-nfs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-direct
  volumeName: grafana-data-nfs
  resources:
    requests:
      storage: 10Gi

---
# Name must match the StatefulSet volumeClaimTemplate pattern.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-direct
  volumeName: prometheus-data-nfs
  resources:
    requests:
      storage: 20Gi
